# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/modules/monitor.conf
source = ~/.config/hypr/modules/program.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/permissions.conf
source = ~/.config/hypr/modules/decoration.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/layouts.conf
source = ~/.config/hypr/modules/misc.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/binds.conf

