# Modifier key
set $mod Mod4

# Font
font pango:Zed Mono Nerd Font 10

# Floating modifier
floating_modifier $mod

# Remove window title bars
default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart
