# XDG autostart applications
exec --no-startup-id dex-autostart --autostart --environment i3

# Lock screen before suspend
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# Network manager tray
exec --no-startup-id nm-applet

# Bluetooth tray
exec --no-startup-id blueman-applet

# picom setup
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf

# wallpaper setup
exec_always --no-startup-id feh --randomize --bg-fill ~/Pictures/wallpapers/*

# copyq, clipboard deamon
exec_always --no-startup-id "copyq --start-server"
