# Terminal
bindsym $mod+Return exec alacritty

# Application launcher rofi
bindsym $mod+d exec rofi -show drun
bindsym $mod+Shift+d exec rofi -show run
bindsym $mod+Tab exec rofi -show window

# File manager
bindsym $mod+e exec thunar

# Browser
bindsym $mod+Shift+Return exec chromium-browser

# zed editor
bindsym $mod+z exec zed

# Kill focused window
bindsym $mod+q kill

# Reload / restart i3
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart

# Screenshot
bindsym Print exec flameshot gui

# Audio controls
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle

# Brightness controls
bindsym XF86MonBrightnessUp exec brightnessctl set +5%
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-

# copyq, clipboard
bindsym $mod+Shift+v exec --no-startup-id "copyq show"
