# Rosé Pine Moon Color Palette
set $base           #232136
set $surface        #2a283e
set $overlay        #393552
set $muted          #6e6a86
set $subtle         #908caa
set $text           #e0def4
set $love           #eb6f92
set $gold           #f6c177
set $rose           #ea9a97
set $pine           #3e8fb0
set $foam           #9ccfd8
set $iris           #c4a7e7
set $highlight_low  #2a283e
set $highlight_med  #44415a
set $highlight_high #56526e


# i3 Window Coloring (class          border          backgr.         text            indicator       child_border)
client.focused                       $iris           $iris           $base           $rose           $iris
client.focused_inactive              $surface        $surface        $subtle         $highlight_med  $surface
client.unfocused                     $base           $base           $muted          $highlight_low  $base
client.urgent                        $love           $love           $base           $love           $love
