bar {
    position top
    status_command i3status
    tray_output primary

    colors {
        background $base
        statusline $text
        separator  $muted

        # Class            Border          Background      Text
        focused_workspace  $iris           $iris           $base
        active_workspace   $surface        $surface        $text
        inactive_workspace $base           $base           $muted
        urgent_workspace   $love           $love           $base
    }
}
